version: '3'

services:
  db:
    image: postgres:13.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DATABASE: pear-it
      POSTGRES_ROOT_PASSWORD: pear-it
      POSTGRES_USER: pear-it
      POSTGRES_PASSWORD: pear-it
